---
driver: 
  name: vagrant

platforms:
- name: centos-6

suites:
- name: default
  run_list:
  - recipe[keepalived_test::default]
  - recipe[keepalived_test::configured]
  - recipe[keepalived_test::virtual_server_provider_create]
  - recipe[keepalived_test::chkscript_provider_create]
  - recipe[keepalived_test::vrrp_provider_create]
  attributes: {developer_mode: true}
