--- 
lint_and_unit: 
  - delivery
  - danger
  - lint-yaml
  - lint-markdown
orbs: 
  kitchen: sous-chefs/kitchen@1
version: 2.1
workflows: 
  kitchen: 
    jobs: 
      - 
        kitchen/yamllint: 
          name: lint-yaml
      - 
        kitchen/mdlint: 
          name: lint-markdown
      - 
        kitchen/danger: 
          context: Danger
          name: danger
      - 
        kitchen/delivery: 
          name: delivery
      - 
        kitchen/dokken-single: 
          name: default-centos-6
          platform: centos-6
          requires: 
            - delivery
            - danger
          suite: default
      - 
        kitchen/dokken-single: 
          name: default-centos-7
          platform: centos-7
          requires: 
            - delivery
            - danger
          suite: default
      - 
        kitchen/dokken-single: 
          name: default-debian-8
          platform: debian-8
          requires: 
            - delivery
            - danger
          suite: default
      - 
        kitchen/dokken-single: 
          name: default-debian-9
          platform: debian-9
          requires: 
            - delivery
            - danger
          suite: default
      - 
        kitchen/dokken-single: 
          name: default-ubuntu-1604
          platform: ubuntu-1604
          requires: 
            - delivery
            - danger
          suite: default
